# Generated by Django 5.1.1 on 2024-09-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('children', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('doctor', 'child', 'slot_start', 'slot_end', 'date')},
        ),
    ]
