# Generated by Django 5.1.1 on 2024-11-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_tele_medicine_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tele_medicine_doctor',
        ),
    ]
