# Generated by Django 5.1.1 on 2024-11-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
        migrations.RenameField(
            model_name='child',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='child',
            name='last_name',
        ),
        migrations.AddField(
            model_name='child',
            name='insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
