# Generated by Django 5.1.1 on 2024-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_remove_child_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
