# Generated by Django 5.1.1 on 2024-11-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0005_child_insurance_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
