# Generated by Django 5.1.1 on 2024-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0008_documents_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='UAE_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='child_id_number',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
