# Generated by Django 5.1.1 on 2024-12-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0010_documents_parent_alter_documents_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
