# Generated by Django 5.1.1 on 2024-12-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0011_documents_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='insurance_number',
            field=models.CharField(blank=True, choices=[('NAS', 'NAS'), ('METLIFE', 'METLIFE'), ('NEXTCARE', 'NEXTCARE'), ('GLOBEMED', 'GLOBEMED'), ('ADNIC', 'ADNIC'), ('OPEN_JET', 'OPEN JET'), ('DAMAN', 'DAMAN'), ('THIQA', 'THIQA'), ('AL_KHAZNA', 'AL KHAZNA'), ('AXA', 'AXA'), ('NEURON', 'NEURON'), ('MEDNET', 'MEDNET'), ('SUKOON', 'SUKOON'), ('WEALTH_INTL', 'Wealth International'), ('PENTACARE', 'Pentacare'), ('AL_MADALLAH', 'AL Madallah'), ('FMC_METLIFE', 'FMC - Metlife'), ('MAX_CARE', 'Max Care'), ('AFIYA_TPA', 'Afiya TPA'), ('NGI_HEALTHNET', 'NGI Healthnet'), ('IRIS', 'IRIS'), ('MSH', 'MSH')], max_length=50, null=True),
        ),
    ]
