# Generated by Django 5.1.1 on 2024-12-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0014_vaccination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='Vaccination_date',
            new_name='vaccination_date',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='Vaccination_name',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='age_group',
            field=models.CharField(choices=[('after_birth', 'After Birth'), ('end_2_month', 'End of 2 Months'), ('end_4_month', 'End of 4 Months'), ('end_6_month', 'End of 6 Months'), ('end_12_month', 'End of 12 Months'), ('end_18_month', 'End of 18 Months'), ('grade_a', 'Grade A'), ('grade_8', 'Grade 8'), ('grade_11', 'Grade 11')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccination_name',
            field=models.CharField(choices=[('BCG', 'BCG'), ('Hepatitis B', 'Hepatitis B'), ('Hexavalent', 'Hexavalent (DTaP, Hib, Hep B, IPV)'), ('PCV', 'PCV'), ('Rotavirus', 'Rotavirus'), ('NMR-1', 'NMR-1'), ('Varicella-1', 'Varicella-1'), ('bOPV', 'bOPV'), ('DTaP-Hib-IPV', 'DTaP-Hib-IPV'), ('MMR-2', 'MMR-2'), ('MMR-3', 'MMR-3'), ('Varicella-2', 'Varicella-2'), ('DTaP-IPV', 'DTaP-IPV'), ('HPV', 'HPV (Female)'), ('Tdap', 'Tdap'), ('MCV', 'MCV')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
