# Generated by Django 5.1.1 on 2024-11-21 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0007_alter_child_relation'),
        ('leaves', '0002_sickleaverequestview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickLeaveRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child')),
            ],
        ),
    ]
