# Generated by Django 5.1.1 on 2024-11-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_towhomitmaycocern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='towhomitmaycocern',
            old_name='cocern',
            new_name='concern',
        ),
    ]
