# Generated by Django 5.1.1 on 2024-11-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_teledoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='tele_medicine_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
