# Generated by Django 5.1.1 on 2024-11-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='digital_consult',
        ),
    ]
