# Generated by Django 5.1.1 on 2024-12-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_doctor_digital_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
