# Generated by Django 5.1.1 on 2024-12-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_alter_doctor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
