# Generated by Django 5.1.1 on 2024-11-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='uploads/pdfs/')),
                ('urn_number', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
