# Generated by Django 5.1.1 on 2024-12-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedpdf',
            name='urn_number',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
