# Generated by Django 5.1.1 on 2024-12-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR', '0002_alter_uploadedpdf_urn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='category',
            field=models.CharField(choices=[('medical_report', 'Medical Report'), ('sick_leave', 'Sick Leave'), ('parent_sick_leave', 'Parent Sick Leave'), ('prescription', 'Prescription'), ('lab_report', 'Lab Report')], default='medical_report', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='urn_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
